### ISSUE TITLE
Owner error log /var/log/asterisk/issabelpbx.log

### ISSUE THREAD

**Issue by marcoadasilvaa** [IssabelFoundation/pbx#1]
After clean installation and access any option, the log said:

**tail -n 50 /var/log/httpd/ssl_error_log** 
[Mon Jun 26 13:39:38.210015 2017] [:error] [pid 4057] [client 192.168.10.120:44394] PHP Warning:  file_put_contents(/var/log/asterisk/issabelpbx.log): failed to open stream: Permission denied in /var/www/html/admin/libraries/utility.functions.php on line 98, referer: https://192.168.10.157/
[Mon Jun 26 13:39:38.210066 2017] [:error] [pid 4057] [client 192.168.10.120:44394] PHP Warning:  file_put_contents(/var/log/asterisk/issabelpbx.log): failed to open stream: Permission denied in /var/www/html/admin/libraries/utility.functions.php on line 98, referer: https://192.168.10.157/
[Mon Jun 26 13:39:38.210107 2017] [:error] [pid 4057] [client 192.168.10.120:44394] PHP Warning:  file_put_contents(/var/log/asterisk/issabelpbx.log): failed to open stream: Permission denied in /var/www/html/admin/libraries/utility.functions.php on line 98, referer: https://192.168.10.157/
[Mon Jun 26 13:39:43.909488 2017] [access_compat:error] [pid 4057] [client 192.168.10.120:44394] AH01797: client denied by server configuration: /var/www/html/admin/index.html, referer: https://192.168.10.157/index.php?menu=pbxadmin

**ls -lha /var/log/asterisk/**
total 556K
drwxrwxr-x.  5 asterisk asterisk 4.0K Jun 26 13:09 .
drwxr-xr-x. 15 root     root     4.0K Jun 26 13:11 ..
drwxrwxr-x.  2 asterisk asterisk 4.0K Jun 26 12:54 cdr-csv
drwxrwxr-x.  2 asterisk asterisk 4.0K Nov 24  2016 cdr-custom
drwxrwxr-x.  2 asterisk asterisk 4.0K Nov 24  2016 cel-custom
-rw-rw-r--   1 asterisk asterisk 465K Jun 26 13:24 full
-rw-rw-r--.  1 root root 1.8K Jun 26 13:09 issabelpbx_debug
-rw-rw-r--   1 root root 1.6K Jun 26 13:09 issabelpbx.log
-rw-rw-r--   1 asterisk asterisk 2.0K Jun 26 13:09 master.db
-rw-rw-r--   1 asterisk asterisk  50K Jun 26 13:49 messages
-rw-rw-r--   1 asterisk asterisk  116 Jun 26 13:24 queue_log

Solution:

run 

**amportal chown**

ls -lha /var/log/asterisk/
total 556K
drwxrwxr-x.  5 asterisk asterisk 4.0K Jun 26 13:09 .
drwxr-xr-x. 15 root     root     4.0K Jun 26 13:11 ..
drwxrwxr-x.  2 asterisk asterisk 4.0K Jun 26 12:54 cdr-csv
drwxrwxr-x.  2 asterisk asterisk 4.0K Nov 24  2016 cdr-custom
drwxrwxr-x.  2 asterisk asterisk 4.0K Nov 24  2016 cel-custom
-rw-rw-r--   1 asterisk asterisk 465K Jun 26 13:24 full
-rw-rw-r--.  1 asterisk asterisk 1.8K Jun 26 13:11 issabelpbx_debug
-rw-rw-r--   1 asterisk asterisk 1.6K Jun 26 13:49 issabelpbx.log
-rw-rw-r--   1 asterisk asterisk 2.0K Jun 26 13:09 master.db
-rw-rw-r--   1 asterisk asterisk  50K Jun 26 13:49 messages
-rw-rw-r--   1 asterisk asterisk  116 Jun 26 13:24 queue_log

**Comment by besfortoruci** [comment]
After I did amportal chown, I got new error now:

[FATAL] Unable to connect to Asterisk Manager from /var/lib/asterisk/bin/retrieve_conf, aborting

**Comment by asternic** [comment]
Thanks.. next release will do the chown of files after initial install setup. @bestfortoruci, the error you see has nothing to do with doing amportal chown.

Best regards,
